question_data = [{"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "MacOS is based on Linux.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "Windows is a monolithic kernel.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "The first computer bug was formed by faulty wires.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "It is not possible to format a write-protected DVD-R Hard Disk.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "In Python the print function can only print literal values.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "The last Windows operating system to be based on the Windows 9x kernel was Windows 98.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "Android versions are named in alphabetical order.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "The CPU is responsible for executing instructions for the computer.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                  "question": "Ada Lovelace is often considered the first computer programmer.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                  "question": "HTML stands for Hypertext Markup Language.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                  "question": "The logo for Snapchat is a Bell.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                  "question": "Time on Computers is measured via the EPOX System.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                  "question": "The Windows 7 operating system has six main editions.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                  "question": "Linus Torvalds created Linux and Git.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                  "question": "The Python programming language gets its name from the British comedy group Monty Python.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                  "question": "Linux was first created as an alternative to Windows XP.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                  "question": "The programming language Python is based off a modified version of JavaScript.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                  "question": "In most programming languages, the operator ++ is equivalent to the statement +=.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}

                 ]

